export default {
    DOUBLE_COUNTER: 'counter/DOUBLE_COUNTER',
    STRING_COUNTER: 'counter/STRING_COUNTER',
    VALUE: 'shared/VALUE',

    MUTATE_INCREMENT_COUNTER: 'counter/MUTATE_INCREMENT_COUNTER',
    MUTATE_DECREMENT_COUNTER: 'counter/MUTATE_DECREMENT_COUNTER',
    MUTATE_UPDATE_VALUE: 'counter/MUTATE_UPDATE_VALUE',

    COUNTER_INCREMENT: 'counter/COUNTER_INCREMENT',
    COUNTER_INCREMENT_ASYNC: 'counter/COUNTER_INCREMENT_ASYNC',
    COUNTER_DECREMENT: 'counter/COUNTER_DECREMENT',
    COUNTER_DECREMENT_ASYNC: 'counter/COUNTER_DECREMENT_ASYNC',
    UPDATE_VALUE: 'shared/UPDATE_VALUE',
}